#!/bin/bash

while IFS=":" read -r user password rest
do
    if [[ $password == "x" ]]; then
        echo "True"
        exit 0
    fi
done < /etc/passwd

echo "False"
script_name=$(basename "$0")
script_name="${script_name%.sh}"

output_file="$(dirname "$0")/output.txt"  
echo "$script_name=$result" >> "$output_file"
