#!/bin/bash

if find / -nouser -print -quit | grep -q .; then
    echo "False"
    find / -nouser -print | awk -F: '{ print $1 " " $3 }'
else
    echo "True"
fi

if find / -nogroup -print -quit | grep -q .; then
    echo "False"
    find / -nogroup -print | awk -F: '{ print $1 " " $3 }'
else
    echo "True"
fi
